language: python

sudo: false

python:
  - "3.5"
  - "3.6"

before_install: pip install pytest-cov

install: pip install -e .

script: make test

notifications:
  email:
    recipients:
      - ajax@bynder.com
    on_success: never
    on_failure: always

deploy:
  provider: pypi
  username: __token__
  password:
    secure: "B2BJNpwc9v0SgC/OQqZcP7OoAA/cAbmw+6mpNp06EspGXQoP4I6V2gOjoh3xly6DbgdSbOYpyFxXJKl0PGpi8Dhp3XH3kROEZWS3lzi6FOvnaY/MzdTsUGQkt0AshYrVKs29awsXg+tAWHRNqMlIUOeN0CiD3T21HANRJu6BppqgU2KYvfQx07UrF9ELyUtQbZJqSO9TLSkDdB+W0clRSgcdXDzE8SorFQQKwtJcGPPePUy4guMmErhuG6RPzE7iiVzarvf+cLBOUwf8OAWltUalGxYmB1XxaJ/x30CDqu1qRf2majuv+Mjc6NcHmewkziIcV8oJ+fW84a0fqD7SpjkKd0KF/H2L+NUPzR8C4n2dwAribiv83GbYXYrWE2V3NeaUvtEWR2lJcBQ4ghIU+W/AhgateQMiOD4zy7MDM7QakBlEDqcxRPySSDWpPWAalRxzcX5+60X60u1zCghFA/D6ggbAt7/VTe7+bwZAD8KsYT81lYyqXENq0wtjBzLxlICzjM5tKrKd5ujEbMyjIQxHJl8K5VImvS+WZi88dJSyU3EmBhTSbm/kL2pzz/he7dd/tDdSop1FybFYcq9mDFqPcRT1YHGtr9g23LQQcNalyWlnYWfQoiGjQovdtHWoBNprro/71sO9lLugjRCqeQMnTWm4eKCyaKFvRAMfjd0="
  on:
    repo: Bynder/bynder-python-sdk
    branch: stage