language: python

python: "3.6"  # or the highest if we update the python list

before_install: pip install pytest-cov

install: pip install -e .

script: make test

notifications:
  email:
    recipients:
      - ajax@bynder.com
    on_success: never
    on_failure: always

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "cuqVZZRpISkCm8jJ2yqTlhxxtEyDSbkz+JOTdo1hChFx1zVadmNek9aP1GZzzAYyoi9UFDw3xyuGhVEwgQAIPSg0PPPyVZlexHO635kAaEsHg3jH16B5dR1QXGE7hYiNGNEskxfFqvV9QYn9ILLacg90fNUDPYfLjouOnbcJ9rQNILDljED7GFxfDrrWG+RcJwacdtZDcPPZoVpOkpsCxdtQHudKl8wy9St9PTccEe0IIfrTDxOusz//SpbIA+6fmp/nzsf6cHD3o4x3tT4GB8srtliwHXJmYaPJqtDtqYHE5+lD/Oar38+z6FzCftcf+g6INab3em+ZkjwZSnhAKKYeNxiw16MEa8f+Xlz36BVER2MT/V0jewVffaCPUOZqsUhkSefS/egPceC8I3X1fEfX/hEO/SJILAALgf5c4CFNYJPwWDzg5E2oOgshwOomG4G7MJnNzUglf7y/gaCXxAtRGyXHbtP0Iaz2W03FA8a/umWi/xjcrLVH6dP7M7plkOSWZTXr3WD1LKA6cMzm5w97ZL93dSjSWhbWJV79nted1G4rWmbIgILLvPptMkySrivvDqOV3LRRtgV+B8JFn1S2XBtY2IMQoNo0CZgS0LULayvKP7QAQ1hpS2N0f7LA76cj7gxe2zBuLVlt1tkYEH888SvveSdr994r3XSJmRQ="
  distributions: "bdist_wheel"
  on:
    branch: stage