language: python

sudo: false

python:
  - "3.5"
  - "3.6"

before_install: pip install pytest-cov

install: pip install -e .

script: make test

notifications:
  email:
    recipients:
      - ajax@bynder.com
    on_success: never
    on_failure: always

deploy:
  provider: pypi
  username: __token__
  password:
    secure: $PYPI_API_TOKEN
  on:
    repo: Bynder/bynder-python-sdk
    branch: stage